events {
    worker_connections 1024;
}

http {
    # 1. 強制將所有 HTTP 流量轉向 HTTPS
    server {
        listen 80;
        server_name marshuang.me www.marshuang.me;
        return 301 https://marshuang.me$request_uri;
    }

    # 2. HTTPS 伺服器
    server {
        listen 443 ssl; # 監聽 443 加密埠
        server_name marshuang.me www.marshuang.me;

        # SSL 憑證路徑 (這是容器內部的路徑)
        ssl_certificate /etc/letsencrypt/live/marshuang.me/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/marshuang.me/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location = /favicon.ico {
            access_log off;
            log_not_found off;
            return 204;
        }

        location / {
            proxy_pass http://app:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}